Repository IujyrinoT2/Magazin-ASD, pull requests merged in 2021-12, with the labels that each got.

#12 Implementare functie stergere produs
  .idea/inspectionProfiles/Project_Default.xml
  main.cpp
Labels: Review

#13 #5 Creare AfisareDetaliiProdus() si CautareProdus()
  .idea/.name
  main.cpp
  out/build/x64-Debug/.cmake/api/v1/query/client-MicrosoftVS/query.json
  out/build/x64-Debug/.cmake/api/v1/reply/cache-v2-49e83b71efe544291c08.json
  out/build/x64-Debug/.cmake/api/v1/reply/cmakeFiles-v1-40d23cd30ccd69671fe0.json
  out/build/x64-Debug/.cmake/api/v1/reply/codemodel-v2-36f3b1bb24b4ee0c116f.json
  out/build/x64-Debug/.cmake/api/v1/reply/index-2021-12-06T13-43-48-0666.json
  out/build/x64-Debug/.cmake/api/v1/reply/target-Magazin_ASD-Debug-39249ea4d703593286d0.json
  out/build/x64-Debug/.cmake/api/v1/reply/toolchains-v1-4258a3316aca72c6c3ff.json
  out/build/x64-Debug/CMakeCache.txt
  out/build/x64-Debug/CMakeFiles/3.20.21032501-MSVC_2/CMakeCCompiler.cmake
  out/build/x64-Debug/CMakeFiles/3.20.21032501-MSVC_2/CMakeCXXCompiler.cmake
  out/build/x64-Debug/CMakeFiles/3.20.21032501-MSVC_2/CMakeDetermineCompilerABI_C.bin
  out/build/x64-Debug/CMakeFiles/3.20.21032501-MSVC_2/CMakeDetermineCompilerABI_CXX.bin
  out/build/x64-Debug/CMakeFiles/3.20.21032501-MSVC_2/CMakeRCCompiler.cmake
  out/build/x64-Debug/CMakeFiles/3.20.21032501-MSVC_2/CMakeSystem.cmake
  out/build/x64-Debug/CMakeFiles/3.20.21032501-MSVC_2/CompilerIdC/CMakeCCompilerId.c
  out/build/x64-Debug/CMakeFiles/3.20.21032501-MSVC_2/CompilerIdCXX/CMakeCXXCompilerId.cpp
  out/build/x64-Debug/CMakeFiles/CMakeOutput.log
  out/build/x64-Debug/CMakeFiles/ShowIncludes/foo.h
  out/build/x64-Debug/CMakeFiles/ShowIncludes/main.c
  out/build/x64-Debug/CMakeFiles/TargetDirectories.txt
  out/build/x64-Debug/CMakeFiles/cmake.check_cache
  out/build/x64-Debug/CMakeFiles/rules.ninja
  out/build/x64-Debug/Testing/Temporary/LastTest.log
  out/build/x64-Debug/VSInheritEnvironments.txt
  out/build/x64-Debug/build.ninja
  out/build/x64-Debug/cmake_install.cmake
Labels: Review

#28 #27-Rezolvare bug daca numele produsului introdus are spatiu
  Lista.cpp
  Meniu.cpp
Labels: bug

#41 #38 Validare date
  Lista.cpp
  Lista.h
  Produs.h
Labels: enhancement
